'use strict';

const APP_VERSION='1.1.0';
const DB_NAME='boothboss';
const STORES=['events','categories','items','sales','payments','customers','inventoryAdjustments','settings'];
const DATA_STORES=STORES.filter(s=>s!=='settings');
const PAYMENT_METHODS=['cash','card','Venmo','Cash App','Zelle','other'];
let db,routeState={page:'home',id:''},cart=new Map(),tourIndex=-1;
const DEMO_PREFIX='demo_',DEMO_MARKER='boothboss_demo_v1';
const TOUR_STEPS=[
  {title:'Home & your current event',text:'Home shows today’s open event, sales total, payment mix, and recent receipts.'},
  {title:'Catalog',text:'Add products, group them into categories, set prices, and optionally track quantities.'},
  {title:'Sell with Quick Sale',text:'Open Sell, tap items into the cart, then choose a payment method. Walk-up sales can stay anonymous.'},
  {title:'Events & closeout',text:'Plan and start a pop-up in Events. Closeout shows sales, payment mix, booth fee, result, and top sellers.'},
  {title:'Customers are optional',text:'Save contact details only when useful. Named purchases build history; ordinary walk-ups need no customer.'},
  {title:'Receipts',text:'Receipts can be opened, shared, downloaded, or printed, and remain available from events and search.'},
  {title:'Backup & restore',text:'Settings downloads a complete backup and validates a restore before replacing current data.'},
  {title:'Your data stays here',text:'BoothBoss works offline. Records live in this browser profile on this device, so download backups regularly. Restart this tour from Settings anytime.'}
];
const app=document.querySelector('#app');
const uid=prefix=>`${prefix}_${crypto.randomUUID()}`;
const now=()=>new Date().toISOString();
const today=()=>now().slice(0,10);
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const money=v=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(Number(v)||0);
const dateText=v=>v?new Date(v.length===10?`${v}T12:00:00`:v).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'}):'—';
const dateTime=v=>v?new Date(v).toLocaleString(undefined,{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}):'—';
const num=v=>Number(v)||0;

function openDB(){return new Promise((resolve,reject)=>{const request=indexedDB.open(DB_NAME,1);request.onupgradeneeded=()=>{for(const name of STORES)if(!request.result.objectStoreNames.contains(name))request.result.createObjectStore(name,{keyPath:'id'});};request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});}
function store(name,mode='readonly'){return db.transaction(name,mode).objectStore(name);}
function all(name){return new Promise((resolve,reject)=>{const r=store(name).getAll();r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
function get(name,id){return new Promise((resolve,reject)=>{const r=store(name).get(id);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});}
function put(name,value){return new Promise((resolve,reject)=>{const r=store(name,'readwrite').put(value);r.onsuccess=()=>resolve(value);r.onerror=()=>reject(r.error);});}
function remove(name,id){return new Promise((resolve,reject)=>{const r=store(name,'readwrite').delete(id);r.onsuccess=()=>resolve();r.onerror=()=>reject(r.error);});}
function clear(name){return new Promise((resolve,reject)=>{const r=store(name,'readwrite').clear();r.onsuccess=()=>resolve();r.onerror=()=>reject(r.error);});}
async function setting(id,fallback=''){return (await get('settings',id))?.value??fallback;}
async function snapshot(){return Object.fromEntries(await Promise.all(STORES.map(async s=>[s,await all(s)])));}
function saleTotals(sale){const subtotal=(sale.line_items||[]).reduce((sum,l)=>sum+num(l.quantity)*num(l.unit_price),0);const discount=Math.min(subtotal,Math.max(0,num(sale.discount)));const taxable=Math.max(0,subtotal-discount);const tax=taxable*Math.max(0,num(sale.tax_rate))/100;return{subtotal,discount,tax,total:taxable+tax};}
function eventSummary(event,sales,payments){const own=sales.filter(s=>s.event_id===event.id&&!s.voided_at);const ids=new Set(own.map(s=>s.id));const pays=payments.filter(p=>ids.has(p.sale_id));const split=method=>pays.filter(p=>p.method===method).reduce((n,p)=>n+num(p.amount),0);const gross=own.reduce((n,s)=>n+saleTotals(s).total,0);const units=own.reduce((n,s)=>n+(s.line_items||[]).reduce((x,l)=>x+num(l.quantity),0),0);const product=new Map();for(const s of own)for(const l of s.line_items||[])product.set(l.item_name,(product.get(l.item_name)||0)+num(l.quantity));return{gross,transactions:own.length,units,cash:split('cash'),card:split('card'),other:pays.filter(p=>!['cash','card'].includes(p.method)).reduce((n,p)=>n+num(p.amount),0),fee:num(event.booth_fee),result:gross-num(event.booth_fee),top:[...product].sort((a,b)=>b[1]-a[1]).slice(0,5)};}

async function reconcile(){
  const [events,sales,payments]=await Promise.all(['events','sales','payments'].map(all));
  const active=events.filter(e=>e.status==='active').sort((a,b)=>(b.started_at||b.updated_at).localeCompare(a.started_at||a.updated_at));
  for(let i=1;i<active.length;i++){active[i].status='planned';active[i].started_at=null;active[i].updated_at=now();await put('events',active[i]);}
  for(const event of events){const next=eventSummary(event,sales,payments);if(JSON.stringify(event.summary)!==JSON.stringify(next)){event.summary=next;event.updated_at=now();await put('events',event);}}
}

function toast(message){const el=document.querySelector('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),2400);}
function go(page,id=''){const next=[page,id].filter(Boolean).join('/');if(location.hash.slice(1)===next)render();else location.hash=next;}
function pageHead(kicker,title,action=''){return `<div class="page-head"><div><div class="eyebrow">${esc(kicker)}</div><h1>${esc(title)}</h1></div>${action}</div>`;}
function empty(text){return `<div class="empty">${esc(text)}</div>`;}
function badge(status){return `<span class="badge ${esc(status)}">${esc(status)}</span>`;}
function input(name,label,value='',type='text',required=false,extra=''){return `<div class="field"><label for="${name}">${esc(label)}</label><input id="${name}" name="${name}" type="${type}" value="${esc(value)}" ${required?'required':''} ${extra}></div>`;}
function textarea(name,label,value=''){return `<div class="field"><label for="${name}">${esc(label)}</label><textarea id="${name}" name="${name}">${esc(value)}</textarea></div>`;}
function select(name,label,options,value=''){return `<div class="field"><label for="${name}">${esc(label)}</label><select id="${name}" name="${name}">${options.map(o=>`<option value="${esc(o.value??o)}" ${(o.value??o)===value?'selected':''}>${esc(o.label??o)}</option>`).join('')}</select></div>`;}
function openDialog(title,body){document.querySelector('dialog')?.remove();document.body.insertAdjacentHTML('beforeend',`<dialog><div class="dialog-head"><h2>${esc(title)}</h2><button class="close" data-action="close-dialog" aria-label="Close">×</button></div><div class="dialog-body">${body}</div></dialog>`);document.querySelector('dialog').showModal();}
function closeDialog(){document.querySelector('dialog')?.close();document.querySelector('dialog')?.remove();}
function renderTour(){document.querySelector('#tour-card')?.remove();if(tourIndex<0)return;const step=TOUR_STEPS[tourIndex];document.body.insertAdjacentHTML('beforeend',`<aside id="tour-card" class="tour-card" aria-live="polite"><div class="eyebrow">Quick tour · ${tourIndex+1} of ${TOUR_STEPS.length}</div><h2>${esc(step.title)}</h2><p>${esc(step.text)}</p><div class="tour-actions"><button class="button small secondary" data-action="skip-tour">Skip</button>${tourIndex?'<button class="button small secondary" data-action="previous-tour">Back</button>':''}<button class="button small" data-action="next-tour">${tourIndex===TOUR_STEPS.length-1?'Done':'Next'}</button></div></aside>`);}
function startTour(){tourIndex=0;renderTour();}
function skipTour(){tourIndex=-1;document.querySelector('#tour-card')?.remove();}
function moveTour(change){tourIndex+=change;if(tourIndex<0||tourIndex>=TOUR_STEPS.length)return skipTour();renderTour();}
function activeNav(page){document.querySelectorAll('[data-nav]').forEach(n=>n.classList.toggle('active',n.dataset.nav===page||(page==='receipt'&&n.dataset.nav==='events')||(['customers','settings','inventory'].includes(page)&&n.dataset.nav==='more')));}
async function route(){const [page='home',id='']=location.hash.slice(1).split('/');routeState={page,id:decodeURIComponent(id)};await render();}
async function render(){activeNav(routeState.page);app.innerHTML='<div class="loading">Opening your booth…</div>';try{const handlers={home:renderHome,sell:renderSell,catalog:renderCatalog,events:renderEvents,event:renderEvent,receipt:renderReceipt,more:renderMore,customers:renderCustomers,customer:renderCustomer,inventory:renderInventory,settings:renderSettings,search:renderSearch};await(handlers[routeState.page]||renderHome)();app.focus({preventScroll:true});scrollTo(0,0);}catch(error){console.error(error);app.innerHTML=`${pageHead('Error','Something went wrong')}<div class="notice">${esc(error.message)}</div>`;}}

async function getActive(){return (await all('events')).find(e=>e.status==='active');}
async function renderHome(){await reconcile();const d=await snapshot(),active=d.events.find(e=>e.status==='active');if(!active){const next=d.events.filter(e=>e.status==='planned').sort((a,b)=>(a.date||'').localeCompare(b.date||''))[0];app.innerHTML=`<section class="hero"><div class="eyebrow">Ready when you are</div><h1>Set up your booth.<br>Tap what sells.</h1><p>Start an event to open the quick-sale counter.</p><div class="hero-actions"><button class="button" data-action="${next?'start-event':'new-event'}" ${next?`data-id="${next.id}"`:''}>${next?`Start ${esc(next.name)}`:'Create an event'}</button></div></section>${quickLinks()}`;return;}const s=eventSummary(active,d.sales,d.payments);app.innerHTML=`<section class="hero"><div class="row"><div><div class="eyebrow">Booth is open</div><h1>${esc(active.name)}</h1><p>${dateText(active.date)}${active.location?` · ${esc(active.location)}`:''}</p></div>${badge('active')}</div><div class="hero-total">${money(s.gross)}</div><p>${s.transactions} ${s.transactions===1?'sale':'sales'} · ${s.units} units</p><div class="hero-actions"><button class="button" data-nav="sell">Quick sale</button><button class="button secondary" data-open="event:${active.id}">View event</button></div></section><div class="stats"><div class="stat"><small>Cash</small><strong>${money(s.cash)}</strong></div><div class="stat"><small>Card</small><strong>${money(s.card)}</strong></div><div class="stat"><small>Other</small><strong>${money(s.other)}</strong></div></div>${quickLinks()}${recentSales(d.sales.filter(x=>x.event_id===active.id),d.customers)}`;}
function quickLinks(){return `<div class="quick-grid"><button class="quick" data-nav="sell"><span>Sale</span>Tap items fast</button><button class="quick" data-action="new-item"><span>Item</span>Add inventory</button><button class="quick" data-action="new-event"><span>Event</span>Plan the next booth</button><button class="quick" data-nav="inventory"><span>Stock</span>Adjust quantities</button></div>`;}
function recentSales(sales,customers){const cm=Object.fromEntries(customers.map(c=>[c.id,c]));const rows=sales.filter(s=>!s.voided_at).sort((a,b)=>b.created_at.localeCompare(a.created_at)).slice(0,5);return `<section class="section"><div class="section-head"><h2>Recent sales</h2><span class="count">${rows.length}</span></div><div class="stack">${rows.length?rows.map(s=>`<button class="card" data-open="receipt:${s.id}"><div class="card-top"><div><strong>${esc(s.sale_number)}</strong><div class="meta">${dateTime(s.created_at)} · ${esc(cm[s.customer_id]?.name||'Walk-up')}</div></div><span class="amount">${money(saleTotals(s).total)}</span></div></button>`).join(''):empty('No sales at this event yet.')}</div></section>`;}

async function renderSell(){const [active,items,categories,settings]=await Promise.all([getActive(),all('items'),all('categories'),all('settings')]);if(!active){app.innerHTML=`${pageHead('Quick sale','No open event')}<div class="notice">Start an event before recording a sale.</div><button class="button" data-nav="events">Go to events</button>`;return;}const available=items.filter(i=>i.active!==false);const categoryTabs=['all',...categories.map(c=>c.id)];app.innerHTML=`${pageHead(active.name,'Quick sale',`<button class="button small secondary" data-action="clear-cart">Clear</button>`)}<div class="sell-layout"><section><input class="search" id="sell-search" placeholder="Search item or SKU" aria-label="Search catalog"><div class="tabs" id="sell-tabs">${categoryTabs.map((id,i)=>`<button class="${i?'':'active'}" data-action="filter-sale" data-filter="${id}">${id==='all'?'All':esc(categories.find(c=>c.id===id)?.name)}</button>`).join('')}</div><div class="product-grid" id="product-grid">${available.length?available.map(item=>productTile(item)).join(''):empty('Add an item to the catalog first.')}</div></section><aside class="cart" id="cart">${await cartHtml(settings)}</aside></div>`;}
function productTile(item){const low=item.track_quantity&&num(item.quantity)<=num(item.low_stock_at);return `<button class="product" data-action="add-cart" data-id="${item.id}" data-category="${esc(item.category_id||'')}" data-search="${esc(`${item.name} ${item.sku||''}`.toLowerCase())}">${item.photo?`<img src="${esc(item.photo)}" alt="">`:''}<div><strong>${esc(item.name)}</strong><div class="meta">${item.track_quantity?`${num(item.quantity)} in stock${low?' · Low':''}`:'Stock not tracked'}</div></div><span class="amount">${money(item.price)}</span></button>`;}
async function cartHtml(){const items=await all('items'),lines=[...cart].map(([id,quantity])=>({item:items.find(i=>i.id===id),quantity})).filter(x=>x.item);const subtotal=lines.reduce((n,l)=>n+num(l.item.price)*l.quantity,0);return `<div class="section-head"><h2>Current sale</h2><span class="count">${lines.reduce((n,l)=>n+l.quantity,0)} items</span></div>${lines.length?lines.map(l=>`<div class="cart-line"><div><strong>${esc(l.item.name)}</strong><span class="meta">${money(l.item.price)} each</span></div><div><div class="qty"><button data-action="cart-minus" data-id="${l.item.id}" aria-label="Remove one">−</button><strong>${l.quantity}</strong><button data-action="cart-plus" data-id="${l.item.id}" aria-label="Add one">+</button></div><div class="amount">${money(l.item.price*l.quantity)}</div></div></div>`).join(''):empty('Tap an item to add it.')}<div class="totals"><div class="row"><span>Subtotal</span><strong id="cart-subtotal">${money(subtotal)}</strong></div></div><button class="button sticky-pay" data-action="checkout" ${lines.length?'':'disabled'}>Checkout · ${money(subtotal)}</button>`;}
async function refreshCart(){const el=document.querySelector('#cart');if(el)el.innerHTML=await cartHtml();}
async function checkoutForm(){const customers=await all('customers'),rate=num(await setting('tax_rate',0));const items=await all('items'),subtotal=[...cart].reduce((n,[id,q])=>n+num(items.find(i=>i.id===id)?.price)*q,0);openDialog('Finish sale',`<form class="form" id="checkout-form">${input('discount','Discount amount',0,'number',false,'min="0" step="0.01"')}${input('tax_rate','Tax rate (%)',rate,'number',false,'min="0" step="0.01"')}${select('method','Payment method',PAYMENT_METHODS,'cash')}${select('customer_id','Customer (optional)',[{value:'',label:'Walk-up / anonymous'},...customers.map(c=>({value:c.id,label:c.name}))],'')}<label class="check"><input type="checkbox" name="receipt"> Open receipt after sale</label><div class="notice">Current subtotal: <strong>${money(subtotal)}</strong></div><button class="button">Complete sale</button></form>`);}

async function renderCatalog(){const [items,categories]=await Promise.all([all('items'),all('categories')]);const cm=Object.fromEntries(categories.map(c=>[c.id,c.name]));app.innerHTML=`${pageHead('What you sell','Catalog',`<button class="button small" data-action="new-item">Add item</button>`)}<input class="search" id="catalog-search" placeholder="Search item or SKU"><div class="actions"><button class="button small secondary" data-action="manage-categories">Categories</button><button class="button small secondary" data-nav="inventory">Inventory</button></div><section class="stack" id="catalog-list">${items.length?items.sort((a,b)=>a.name.localeCompare(b.name)).map(i=>`<button class="card" data-action="edit-item" data-id="${i.id}" data-search="${esc(`${i.name} ${i.sku||''} ${cm[i.category_id]||''}`.toLowerCase())}"><div class="card-top"><div><strong>${esc(i.name)}</strong><div class="meta">${esc(cm[i.category_id]||'Uncategorized')}${i.sku?` · ${esc(i.sku)}`:''}</div><div class="meta">${i.track_quantity?`${num(i.quantity)} in stock`:'Quantity not tracked'}</div></div><span class="amount">${money(i.price)}</span></div></button>`).join(''):empty('Your catalog is empty. Add the first item.')}</section>`;}
async function itemForm(item={}){const cats=await all('categories');openDialog(item.id?'Edit item':'Add item',`<form class="form" id="item-form" data-id="${esc(item.id||'')}">${input('name','Item name',item.name||'','text',true)}<div class="grid-2">${input('sku','SKU (optional)',item.sku||'')}${input('price','Price',item.price??'','number',true,'min="0" step="0.01"')}</div>${select('category_id','Category',[{value:'',label:'Uncategorized'},...cats.map(c=>({value:c.id,label:c.name}))],item.category_id||'')}<div class="field"><label>Photo (optional)</label><input type="file" name="photo" accept="image/*">${item.photo?`<img class="photo-preview" src="${esc(item.photo)}" alt="Current item">`:''}</div><label class="check"><input type="checkbox" name="track_quantity" ${item.track_quantity?'checked':''}> Track quantity</label><div class="grid-2">${input('quantity','Starting / current quantity',item.quantity??0,'number',false,'step="1"')}${input('low_stock_at','Low-stock level',item.low_stock_at??0,'number',false,'min="0" step="1"')}</div><label class="check"><input type="checkbox" name="active" ${item.active!==false?'checked':''}> Available for sale</label><button class="button">Save item</button>${item.id?`<button type="button" class="button danger" data-action="delete-record" data-store="items" data-id="${item.id}">Delete item</button>`:''}</form>`);}
async function categoryManager(){const rows=await all('categories');openDialog('Categories',`<form class="form" id="category-form">${input('name','New category','','text',true)}<button class="button">Add category</button></form><section class="section stack">${rows.length?rows.map(c=>`<div class="card row"><strong>${esc(c.name)}</strong><button class="button small danger" data-action="delete-category" data-id="${c.id}">Delete</button></div>`).join(''):empty('No categories yet.')}</section>`);}

async function renderEvents(){await reconcile();const events=(await all('events')).sort((a,b)=>(b.date||'').localeCompare(a.date||''));app.innerHTML=`${pageHead('Markets & pop-ups','Events',`<button class="button small" data-action="new-event">New event</button>`)}<section class="stack">${events.length?events.map(e=>`<button class="card" data-open="event:${e.id}"><div class="card-top"><div><strong>${esc(e.name)}</strong><div class="meta">${dateText(e.date)}${e.location?` · ${esc(e.location)}`:''}</div></div><div>${badge(e.status)}<div class="amount">${money(e.summary?.gross||0)}</div></div></div></button>`).join(''):empty('Create your first market or pop-up.')}</section>`;}
async function eventForm(event={}){openDialog(event.id?'Edit event':'New event',`<form class="form" id="event-form" data-id="${esc(event.id||'')}">${input('name','Event name',event.name||'','text',true)}<div class="grid-2">${input('date','Date',event.date||today(),'date',true)}${input('booth_fee','Booth fee',event.booth_fee??0,'number',false,'min="0" step="0.01"')}</div>${input('location','Location (optional)',event.location||'')}${textarea('notes','Notes',event.notes||'')}<button class="button">Save event</button>${event.id?`<button type="button" class="button danger" data-action="delete-record" data-store="events" data-id="${event.id}">Delete event</button>`:''}</form>`);}
async function renderEvent(){await reconcile();const event=await get('events',routeState.id);if(!event)return go('events');const [sales,payments,customers]=await Promise.all(['sales','payments','customers'].map(all)),s=eventSummary(event,sales,payments);const top=s.top.map(([name,q],i)=>`<div class="card row"><strong>${i+1}. ${esc(name)}</strong><span>${q} sold</span></div>`).join('');app.innerHTML=`${pageHead(event.status==='closed'?'Closed event':event.status==='active'?'Booth is open':'Planned event',event.name,`<button class="button small secondary" data-action="edit-event" data-id="${event.id}">Edit</button>`)}<div class="card"><div class="row"><div><strong>${dateText(event.date)}</strong><span class="meta">${esc(event.location||'No location')}</span></div>${badge(event.status)}</div><div class="actions">${event.status==='planned'?`<button class="button" data-action="start-event" data-id="${event.id}">Start event</button>`:''}${event.status==='active'?`<button class="button" data-nav="sell">Quick sale</button><button class="button secondary" data-action="close-event" data-id="${event.id}">Close event</button>`:''}${event.status==='closed'?`<button class="button secondary" data-action="reopen-event" data-id="${event.id}">Reopen event</button>`:''}</div></div><section class="section"><div class="section-head"><h2>Closeout</h2></div><div class="closeout-grid"><div class="stat"><small>Gross</small><strong>${money(s.gross)}</strong></div><div class="stat"><small>Transactions</small><strong>${s.transactions}</strong></div><div class="stat"><small>Units sold</small><strong>${s.units}</strong></div><div class="stat"><small>Cash / card / other</small><strong>${money(s.cash)} / ${money(s.card)} / ${money(s.other)}</strong></div><div class="stat"><small>Booth fee</small><strong>−${money(s.fee)}</strong></div><div class="stat"><small>Adjusted result</small><strong class="result">${money(s.result)}</strong></div></div></section><section class="section"><div class="section-head"><h2>Top sellers</h2></div><div class="stack">${top||empty('No sales yet.')}</div></section>${recentSales(sales.filter(x=>x.event_id===event.id),customers)}`;}

async function renderReceipt(){const sale=await get('sales',routeState.id);if(!sale)return go('events');const [event,customer,payments,settings]=await Promise.all([get('events',sale.event_id),sale.customer_id?get('customers',sale.customer_id):null,all('payments'),all('settings')]);const sm=Object.fromEntries(settings.map(s=>[s.id,s.value])),t=saleTotals(sale),pay=payments.find(p=>p.sale_id===sale.id);app.innerHTML=`${pageHead('Sale complete',sale.sale_number,`<button class="button small secondary no-print" data-action="share-receipt" data-id="${sale.id}">Share</button>`)}<article class="card receipt-print"><h2>${esc(sm.business_name||'BoothBoss')}</h2>${sm.business_contact?`<div class="meta">${esc(sm.business_contact)}</div>`:''}<hr><div class="row"><span>${dateTime(sale.created_at)}</span><strong>${esc(event?.name||'Event')}</strong></div><div class="meta">${esc(customer?.name||'Walk-up customer')} · ${esc(pay?.method||'')}</div><section class="section stack">${sale.line_items.map(l=>`<div class="row"><span>${num(l.quantity)} × ${esc(l.item_name)}</span><strong>${money(num(l.quantity)*num(l.unit_price))}</strong></div>`).join('')}</section><div class="totals"><div class="row"><span>Subtotal</span><strong>${money(t.subtotal)}</strong></div>${t.discount?`<div class="row"><span>Discount</span><strong>−${money(t.discount)}</strong></div>`:''}${t.tax?`<div class="row"><span>Tax</span><strong>${money(t.tax)}</strong></div>`:''}<div class="row grand"><span>Total</span><strong>${money(t.total)}</strong></div></div>${sm.receipt_footer?`<p class="footer-note">${esc(sm.receipt_footer)}</p>`:''}</article><div class="actions no-print"><button class="button" data-action="share-receipt" data-id="${sale.id}">Share receipt</button><button class="button secondary" data-action="download-receipt" data-id="${sale.id}">Download</button><button class="button secondary" onclick="print()">Print</button></div>`;}
async function receiptText(id){const sale=await get('sales',id),event=await get('events',sale.event_id),customer=sale.customer_id?await get('customers',sale.customer_id):null,t=saleTotals(sale),business=await setting('business_name','BoothBoss'),footer=await setting('receipt_footer','Thanks for shopping small!');return[business,sale.sale_number,dateTime(sale.created_at),event?.name||'',customer?.name||'Walk-up customer','',...sale.line_items.map(l=>`${l.quantity} x ${l.item_name} @ ${money(l.unit_price)} = ${money(l.quantity*l.unit_price)}`),'',`Subtotal: ${money(t.subtotal)}`,`Discount: ${money(t.discount)}`,`Tax: ${money(t.tax)}`,`Total: ${money(t.total)}`,'',footer].join('\n');}

async function renderMore(){app.innerHTML=`${pageHead('Your back office','More')}<div class="quick-grid"><button class="quick" data-nav="customers"><span>People</span>Customers & history</button><button class="quick" data-nav="inventory"><span>Count</span>Inventory activity</button><button class="quick" data-nav="search"><span>Find</span>Search everything</button><button class="quick" data-nav="settings"><span>Setup</span>Settings & data</button></div>`;}
async function renderCustomers(){const [customers,sales]=await Promise.all(['customers','sales'].map(all));app.innerHTML=`${pageHead('Optional buyer details','Customers',`<button class="button small" data-action="new-customer">Add customer</button>`)}<section class="stack">${customers.length?customers.sort((a,b)=>a.name.localeCompare(b.name)).map(c=>{const own=sales.filter(s=>s.customer_id===c.id&&!s.voided_at);return `<button class="card" data-open="customer:${c.id}"><div class="card-top"><div><strong>${esc(c.name)}</strong><div class="meta">${esc(c.email||c.phone||'No contact details')}</div></div><span>${own.length} purchases</span></div></button>`;}).join(''):empty('Walk-up sales need no customer. Add only when useful.')}</section>`;}
async function customerForm(c={}){openDialog(c.id?'Edit customer':'Add customer',`<form class="form" id="customer-form" data-id="${esc(c.id||'')}">${input('name','Name',c.name||'','text',true)}<div class="grid-2">${input('email','Email (optional)',c.email||'','email')}${input('phone','Phone (optional)',c.phone||'','tel')}</div>${textarea('notes','Notes',c.notes||'')}<button class="button">Save customer</button>${c.id?`<button type="button" class="button danger" data-action="delete-record" data-store="customers" data-id="${c.id}">Delete customer</button>`:''}</form>`);}
async function renderCustomer(){const c=await get('customers',routeState.id);if(!c)return go('customers');const sales=(await all('sales')).filter(s=>s.customer_id===c.id);app.innerHTML=`${pageHead('Customer',c.name,`<button class="button small secondary" data-action="edit-customer" data-id="${c.id}">Edit</button>`)}<div class="card"><div>${esc(c.email||'No email')}</div><div>${esc(c.phone||'No phone')}</div>${c.notes?`<div class="notice">${esc(c.notes)}</div>`:''}</div>${recentSales(sales,[c])}`;}

async function renderInventory(){const [items,adjustments]=await Promise.all(['items','inventoryAdjustments'].map(all));const im=Object.fromEntries(items.map(i=>[i.id,i]));app.innerHTML=`${pageHead('Simple stock ledger','Inventory',`<button class="button small" data-action="new-adjustment">Adjust stock</button>`)}<section class="stack">${items.filter(i=>i.track_quantity).map(i=>`<div class="card row"><div><strong>${esc(i.name)}</strong><div class="meta">${num(i.low_stock_at)>=num(i.quantity)?'Low stock':'In stock'}</div></div><span class="amount">${num(i.quantity)}</span></div>`).join('')||empty('Turn on quantity tracking for catalog items.')}</section><section class="section"><div class="section-head"><h2>Recent adjustments</h2></div><div class="stack">${adjustments.sort((a,b)=>b.created_at.localeCompare(a.created_at)).slice(0,30).map(a=>`<div class="card row"><div><strong>${esc(im[a.item_id]?.name||a.item_name||'Deleted item')}</strong><div class="meta">${esc(a.reason)} · ${dateTime(a.created_at)}</div></div><span class="amount">${a.change>0?'+':''}${a.change}</span></div>`).join('')||empty('No stock movements yet.')}</div></section>`;}
async function adjustmentForm(){const items=(await all('items')).filter(i=>i.track_quantity);openDialog('Adjust inventory',`<form class="form" id="adjustment-form">${select('item_id','Item',items.map(i=>({value:i.id,label:`${i.name} (${num(i.quantity)})`})),'')}${select('reason','Reason',['restock','correction','damage/loss','manual adjustment'],'restock')}${input('change','Quantity change (use negative to subtract)',1,'number',true,'step="1"')}${textarea('note','Note (optional)')}<button class="button" ${items.length?'':'disabled'}>Save adjustment</button></form>`);}

async function renderSettings(){const sm=Object.fromEntries((await all('settings')).map(s=>[s.id,s.value])),hasDemo=(await Promise.all(DATA_STORES.map(all))).some(rows=>rows.some(isDemoRecord));app.innerHTML=`${pageHead('Business & local data','Settings')}<form class="form card" id="settings-form">${input('business_name','Business name',sm.business_name||'')}${input('business_contact','Receipt contact line',sm.business_contact||'')}${input('tax_rate','Default tax rate (%)',sm.tax_rate??0,'number',false,'min="0" step="0.01"')}${textarea('receipt_footer','Receipt footer',sm.receipt_footer||'Thanks for shopping small!')}<button class="button">Save settings</button></form><section class="section"><div class="section-head"><h2>Learn & explore</h2></div><div class="card"><p class="meta">Take a short tour, or add clearly labeled sample records to explore offline. Demo tools never send data anywhere.</p><div class="actions"><button class="button secondary" data-action="start-tour">Tour</button><button class="button secondary" data-action="populate-demo">Populate with Demo Data</button><button class="button danger" data-action="clear-demo" ${hasDemo?'':'disabled'}>Clear Demo Data</button></div></div></section><section class="section"><div class="section-head"><h2>Backup & restore</h2></div><div class="card"><p class="meta">Backup includes every record and locally stored item photo. Restore validates the file, then completely replaces current data.</p><div class="actions"><button class="button secondary" data-action="backup">Download backup</button><label class="button secondary">Restore backup<input id="restore-file" type="file" accept="application/json" hidden></label></div></div></section><section class="section"><div class="section-head"><h2>CSV exports</h2></div><div class="actions">${['events','items','sales','payments','customers','inventoryAdjustments'].map(s=>`<button class="button small secondary" data-action="export-csv" data-store="${s}">${s==='items'?'Catalog':s==='inventoryAdjustments'?'Inventory adjustments':s[0].toUpperCase()+s.slice(1)}</button>`).join('')}</div></section><p class="footer-note">BoothBoss ${APP_VERSION} · Local-first · Temporary neutral PWA icon</p>`;}

async function renderSearch(){const q=routeState.id.toLowerCase();const d=await snapshot(),rows=[];if(q){for(const i of d.items.filter(x=>`${x.name} ${x.sku||''}`.toLowerCase().includes(q)))rows.push({kind:'Item',title:i.name,meta:i.sku||money(i.price),action:`catalog`});for(const e of d.events.filter(x=>`${x.name} ${x.location||''}`.toLowerCase().includes(q)))rows.push({kind:'Event',title:e.name,meta:dateText(e.date),action:`event:${e.id}`});for(const c of d.customers.filter(x=>`${x.name} ${x.email||''} ${x.phone||''}`.toLowerCase().includes(q)))rows.push({kind:'Customer',title:c.name,meta:c.email||c.phone||'',action:`customer:${c.id}`});for(const s of d.sales.filter(x=>`${x.sale_number} ${(x.line_items||[]).map(l=>l.item_name).join(' ')}`.toLowerCase().includes(q)))rows.push({kind:'Sale',title:s.sale_number,meta:money(saleTotals(s).total),action:`receipt:${s.id}`});}app.innerHTML=`${pageHead('Items, SKUs, events, people & sales','Search')}<form id="search-form"><input class="search" name="q" autofocus placeholder="What are you looking for?" value="${esc(routeState.id)}"></form><section class="stack">${q?(rows.length?rows.map(r=>`<button class="card" data-open="${r.action}"><div class="eyebrow">${r.kind}</div><div class="card-top"><strong>${esc(r.title)}</strong><span>${esc(r.meta)}</span></div></button>`).join(''):empty('No matching local records.')):empty('Search by item, SKU, event, customer, or sale number.')}</section>`;}

function fileData(file){return new Promise((resolve,reject)=>{if(!file)return resolve(null);const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(r.error);r.readAsDataURL(file);});}
function download(name,content,type='text/plain'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
async function backup(){const payload={format:'boothboss-backup',version:1,exported_at:now(),data:await snapshot()};download(`boothboss-backup-${today()}.json`,JSON.stringify(payload,null,2),'application/json');}
function validateBackup(payload){if(!payload||payload.format!=='boothboss-backup'||payload.version!==1||!payload.data)throw new Error('This is not a supported BoothBoss backup.');for(const s of STORES)if(!Array.isArray(payload.data[s]))throw new Error(`Backup is missing ${s}.`);for(const s of STORES)for(const r of payload.data[s])if(!r||typeof r!=='object'||typeof r.id!=='string')throw new Error(`Invalid record in ${s}.`);return true;}
async function restore(file){let payload;try{payload=JSON.parse(await file.text());validateBackup(payload);}catch(error){toast(`Restore rejected: ${error.message}`);return;}if(!confirm('Replace ALL BoothBoss data on this device with this backup? This cannot be undone.'))return;for(const s of STORES){await clear(s);for(const record of payload.data[s])await put(s,record);}await reconcile();toast('Backup restored');go('home');}
function csvCell(v){const text=typeof v==='object'&&v!==null?JSON.stringify(v):String(v??'');return `"${text.replaceAll('"','""')}"`;}
async function exportCSV(name){const rows=await all(name);const headers=[...new Set(rows.flatMap(Object.keys))];const csv=[headers.map(csvCell).join(','),...rows.map(r=>headers.map(h=>csvCell(r[h])).join(','))].join('\r\n');download(`boothboss-${name}-${today()}.csv`,csv||'','text/csv');}

function isDemoRecord(record){return record?.demo_marker===DEMO_MARKER&&record.id.startsWith(DEMO_PREFIX);}
function demoDate(daysAgo,hour=12){const d=new Date();d.setHours(hour,0,0,0);d.setDate(d.getDate()-daysAgo);return d.toISOString();}
async function putDemo(storeName,record){const existing=await get(storeName,record.id);if(!existing||isDemoRecord(existing))await put(storeName,{...record,demo_marker:DEMO_MARKER});}
async function reconcileDemoSummaries(){const [events,sales,payments]=await Promise.all(['events','sales','payments'].map(all));for(const event of events.filter(isDemoRecord)){event.summary=eventSummary(event,sales,payments);event.updated_at=now();await put('events',event);}}
async function populateDemoData(){
  const realActive=(await all('events')).some(e=>e.status==='active'&&!isDemoRecord(e));
  const created=demoDate(30),activeAt=demoDate(0,8),closedAt=demoDate(14,17);
  for(const record of [{id:'demo_category_jewelry',name:'[DEMO] Jewelry'},{id:'demo_category_home',name:'[DEMO] Home Goods'}])await putDemo('categories',{...record,created_at:created,updated_at:created});
  for(const record of [
    {id:'demo_item_hoops',name:'[DEMO] Brass Hoops',sku:'DEMO-HOOP',price:28,category_id:'demo_category_jewelry',photo:null,track_quantity:true,quantity:9,low_stock_at:3,active:true},
    {id:'demo_item_candle',name:'[DEMO] Citrus Candle',sku:'DEMO-CANDLE',price:18,category_id:'demo_category_home',photo:null,track_quantity:true,quantity:5,low_stock_at:2,active:true},
    {id:'demo_item_tote',name:'[DEMO] Market Tote',sku:'DEMO-TOTE',price:22,category_id:'demo_category_home',photo:null,track_quantity:false,quantity:0,low_stock_at:0,active:true}
  ])await putDemo('items',{...record,created_at:created,updated_at:activeAt});
  await putDemo('customers',{id:'demo_customer_maya',name:'[DEMO] Maya Chen',email:'maya@example.test',phone:'555-0100',notes:'Demo customer for exploring purchase history.',created_at:created,updated_at:created});
  await putDemo('events',{id:'demo_event_active',name:'[DEMO] Riverside Pop-Up',date:activeAt.slice(0,10),location:'Riverside Market',booth_fee:45,notes:'Demo event — safe to clear in Settings.',status:realActive?'planned':'active',started_at:realActive?null:activeAt,closed_at:null,summary:null,created_at:created,updated_at:activeAt});
  await putDemo('events',{id:'demo_event_closed',name:'[DEMO] Makers Night',date:closedAt.slice(0,10),location:'Old Town Hall',booth_fee:35,notes:'Demo closed event and closeout.',status:'closed',started_at:demoDate(14,10),closed_at:closedAt,summary:null,created_at:created,updated_at:closedAt});
  for(const record of [
    {id:'demo_sale_active_named',sale_number:'DEMO-1001',event_id:'demo_event_active',customer_id:'demo_customer_maya',line_items:[{item_id:'demo_item_hoops',item_name:'[DEMO] Brass Hoops',sku:'DEMO-HOOP',quantity:1,unit_price:28},{item_id:'demo_item_tote',item_name:'[DEMO] Market Tote',sku:'DEMO-TOTE',quantity:1,unit_price:22}],discount:5,tax_rate:0,created_at:demoDate(0,10),voided_at:null},
    {id:'demo_sale_active_walkup',sale_number:'DEMO-1002',event_id:'demo_event_active',customer_id:null,line_items:[{item_id:'demo_item_candle',item_name:'[DEMO] Citrus Candle',sku:'DEMO-CANDLE',quantity:2,unit_price:18}],discount:0,tax_rate:0,created_at:demoDate(0,11),voided_at:null},
    {id:'demo_sale_closed_walkup',sale_number:'DEMO-0901',event_id:'demo_event_closed',customer_id:null,line_items:[{item_id:'demo_item_hoops',item_name:'[DEMO] Brass Hoops',sku:'DEMO-HOOP',quantity:2,unit_price:28}],discount:0,tax_rate:0,created_at:demoDate(14,13),voided_at:null},
    {id:'demo_sale_closed_named',sale_number:'DEMO-0902',event_id:'demo_event_closed',customer_id:'demo_customer_maya',line_items:[{item_id:'demo_item_candle',item_name:'[DEMO] Citrus Candle',sku:'DEMO-CANDLE',quantity:1,unit_price:18},{item_id:'demo_item_tote',item_name:'[DEMO] Market Tote',sku:'DEMO-TOTE',quantity:1,unit_price:22}],discount:0,tax_rate:0,created_at:demoDate(14,15),voided_at:null}
  ])await putDemo('sales',record);
  for(const record of [{id:'demo_payment_1001',sale_id:'demo_sale_active_named',event_id:'demo_event_active',amount:45,method:'card',created_at:demoDate(0,10)},{id:'demo_payment_1002',sale_id:'demo_sale_active_walkup',event_id:'demo_event_active',amount:36,method:'cash',created_at:demoDate(0,11)},{id:'demo_payment_0901',sale_id:'demo_sale_closed_walkup',event_id:'demo_event_closed',amount:56,method:'cash',created_at:demoDate(14,13)},{id:'demo_payment_0902',sale_id:'demo_sale_closed_named',event_id:'demo_event_closed',amount:40,method:'Venmo',created_at:demoDate(14,15)}])await putDemo('payments',record);
  for(const record of [{id:'demo_adjustment_open_hoops',item_id:'demo_item_hoops',item_name:'[DEMO] Brass Hoops',change:12,reason:'restock',note:'Demo opening stock',created_at:created},{id:'demo_adjustment_sale_hoops',item_id:'demo_item_hoops',item_name:'[DEMO] Brass Hoops',change:-3,reason:'sale',sale_id:'demo_sale_active_named',note:'Demo sales',created_at:activeAt},{id:'demo_adjustment_open_candle',item_id:'demo_item_candle',item_name:'[DEMO] Citrus Candle',change:8,reason:'restock',note:'Demo opening stock',created_at:created},{id:'demo_adjustment_sale_candle',item_id:'demo_item_candle',item_name:'[DEMO] Citrus Candle',change:-3,reason:'sale',sale_id:'demo_sale_active_walkup',note:'Demo sales',created_at:activeAt}])await putDemo('inventoryAdjustments',record);
  await reconcileDemoSummaries();
}
async function clearDemoData(){for(const name of DATA_STORES)for(const record of await all(name))if(isDemoRecord(record))await remove(name,record.id);}

async function saveForm(form){const fd=new FormData(form),data=Object.fromEntries(fd),id=form.dataset.id;
  if(form.id==='event-form'){const old=id?await get('events',id):null;await put('events',{...old,id:id||uid('event'),name:data.name,date:data.date,location:data.location,booth_fee:num(data.booth_fee),notes:data.notes,status:old?.status||'planned',started_at:old?.started_at||null,closed_at:old?.closed_at||null,summary:old?.summary||null,created_at:old?.created_at||now(),updated_at:now()});closeDialog();toast('Event saved');return render();}
  if(form.id==='item-form'){const old=id?await get('items',id):null,photo=await fileData(form.photo.files[0]);const quantity=Math.trunc(num(data.quantity)),record={...old,id:id||uid('item'),name:data.name,sku:data.sku,price:num(data.price),category_id:data.category_id||null,photo:photo||old?.photo||null,track_quantity:data.track_quantity==='on',quantity,low_stock_at:Math.max(0,Math.trunc(num(data.low_stock_at))),active:data.active==='on',created_at:old?.created_at||now(),updated_at:now()};await put('items',record);const previous=old?.track_quantity?num(old.quantity):0;if(record.track_quantity&&quantity!==previous)await put('inventoryAdjustments',{id:uid('adj'),item_id:record.id,item_name:record.name,change:quantity-previous,reason:old?'correction':'manual adjustment',note:old?'Quantity changed while editing item':'Opening quantity',created_at:now()});closeDialog();toast('Item saved');return render();}
  if(form.id==='category-form'){await put('categories',{id:uid('category'),name:data.name,created_at:now(),updated_at:now()});closeDialog();toast('Category added');return categoryManager();}
  if(form.id==='customer-form'){const old=id?await get('customers',id):null;await put('customers',{...old,id:id||uid('customer'),name:data.name,email:data.email,phone:data.phone,notes:data.notes,created_at:old?.created_at||now(),updated_at:now()});closeDialog();toast('Customer saved');return render();}
  if(form.id==='settings-form'){for(const [key,value] of Object.entries(data))await put('settings',{id:key,value});toast('Settings saved');return render();}
  if(form.id==='adjustment-form'){const item=await get('items',data.item_id),change=Math.trunc(num(data.change));if(!item)throw new Error('Choose an item.');item.quantity=num(item.quantity)+change;item.updated_at=now();await put('items',item);await put('inventoryAdjustments',{id:uid('adj'),item_id:item.id,item_name:item.name,change,reason:data.reason,note:data.note,created_at:now()});closeDialog();toast('Inventory updated');return render();}
  if(form.id==='checkout-form'){const active=await getActive();if(!active)throw new Error('No active event.');const items=await all('items'),n=num(await setting('sale_next',1)),lines=[];for(const [itemId,quantity] of cart){const item=items.find(i=>i.id===itemId);if(!item)continue;if(item.track_quantity&&num(item.quantity)<quantity&&!confirm(`${item.name} has only ${item.quantity} in stock. Record the sale anyway?`))return;lines.push({item_id:item.id,item_name:item.name,sku:item.sku||'',quantity,unit_price:num(item.price)});}const sale={id:uid('sale'),sale_number:`SALE-${String(n).padStart(5,'0')}`,event_id:active.id,customer_id:data.customer_id||null,line_items:lines,discount:num(data.discount),tax_rate:num(data.tax_rate),created_at:now(),voided_at:null};const total=saleTotals(sale).total;await put('sales',sale);await put('payments',{id:uid('payment'),sale_id:sale.id,event_id:active.id,amount:total,method:data.method,created_at:now()});await put('settings',{id:'sale_next',value:n+1});for(const line of lines){const item=items.find(i=>i.id===line.item_id);if(item.track_quantity){item.quantity=num(item.quantity)-line.quantity;item.updated_at=now();await put('items',item);await put('inventoryAdjustments',{id:uid('adj'),item_id:item.id,item_name:item.name,change:-line.quantity,reason:'sale',sale_id:sale.id,note:sale.sale_number,created_at:now()});}}cart.clear();closeDialog();await reconcile();toast('Sale saved');return data.receipt==='on'?go('receipt',sale.id):go('sell');}
}

async function handleAction(name,el){
  if(name==='start-tour')return startTour();if(name==='skip-tour')return skipTour();if(name==='previous-tour')return moveTour(-1);if(name==='next-tour')return moveTour(1);
  if(name==='populate-demo'){await populateDemoData();toast('Demo data is ready');return render();}
  if(name==='clear-demo'){if(!confirm('Clear only BoothBoss demo data? Your real records will stay untouched.'))return;await clearDemoData();toast('Demo data cleared');return render();}
  if(name==='close-dialog')return closeDialog();if(name==='new-event')return eventForm();if(name==='edit-event')return eventForm(await get('events',el.dataset.id));if(name==='new-item')return itemForm();if(name==='edit-item')return itemForm(await get('items',el.dataset.id));if(name==='manage-categories')return categoryManager();if(name==='new-customer')return customerForm();if(name==='edit-customer')return customerForm(await get('customers',el.dataset.id));if(name==='new-adjustment')return adjustmentForm();
  if(name==='start-event'||name==='reopen-event'){const current=await getActive();if(current&&current.id!==el.dataset.id){if(!confirm(`Close ${current.name} and open this event?`))return;current.status='closed';current.closed_at=now();current.updated_at=now();await put('events',current);}const event=await get('events',el.dataset.id);event.status='active';event.started_at=event.started_at||now();event.closed_at=null;event.updated_at=now();await put('events',event);await reconcile();toast('Event started');return go('sell');}
  if(name==='close-event'){if(!confirm('Close this event and finalize its current closeout? You can reopen it later.'))return;const event=await get('events',el.dataset.id);event.status='closed';event.closed_at=now();event.updated_at=now();await put('events',event);await reconcile();toast('Event closed');return render();}
  if(name==='delete-record'){if(el.dataset.store==='events'&&(await all('sales')).some(s=>s.event_id===el.dataset.id))return toast('Events with sales cannot be deleted');if(!confirm(`Delete this ${el.dataset.store.slice(0,-1)}? This cannot be undone.`))return;await remove(el.dataset.store,el.dataset.id);closeDialog();toast('Record deleted');return go(el.dataset.store==='events'?'events':el.dataset.store==='customers'?'customers':'catalog');}
  if(name==='delete-category'){const used=(await all('items')).some(i=>i.category_id===el.dataset.id);if(used)return toast('Move items out of this category first');if(!confirm('Delete this category?'))return;await remove('categories',el.dataset.id);closeDialog();return categoryManager();}
  if(name==='add-cart'){cart.set(el.dataset.id,(cart.get(el.dataset.id)||0)+1);return refreshCart();}if(name==='cart-plus'){cart.set(el.dataset.id,(cart.get(el.dataset.id)||0)+1);return refreshCart();}if(name==='cart-minus'){const q=(cart.get(el.dataset.id)||0)-1;q>0?cart.set(el.dataset.id,q):cart.delete(el.dataset.id);return refreshCart();}if(name==='clear-cart'){if(cart.size&&confirm('Clear the current sale?')){cart.clear();refreshCart();}return;}if(name==='checkout')return checkoutForm();
  if(name==='filter-sale'){document.querySelectorAll('#sell-tabs button').forEach(b=>b.classList.toggle('active',b===el));filterProducts();return;}if(name==='backup')return backup();if(name==='export-csv')return exportCSV(el.dataset.store);
  if(name==='share-receipt'){const text=await receiptText(el.dataset.id);if(navigator.share)try{return await navigator.share({title:'BoothBoss receipt',text});}catch(error){if(error.name==='AbortError')return;}download(`${el.dataset.id}.txt`,text);return toast('Receipt downloaded');}if(name==='download-receipt'){download(`${el.dataset.id}.txt`,await receiptText(el.dataset.id));return toast('Receipt downloaded');}
}
function filterProducts(){const q=(document.querySelector('#sell-search')?.value||'').toLowerCase(),category=document.querySelector('#sell-tabs .active')?.dataset.filter||'all';document.querySelectorAll('#product-grid .product').forEach(p=>p.hidden=!(p.dataset.search.includes(q)&&(category==='all'||p.dataset.category===category)));}
document.addEventListener('click',async e=>{const nav=e.target.closest('[data-nav]');if(nav){go(nav.dataset.nav);return;}const open=e.target.closest('[data-open]');if(open){const [page,id]=open.dataset.open.split(':');go(page,id);return;}const action=e.target.closest('[data-action]');if(action)try{await handleAction(action.dataset.action,action);}catch(error){console.error(error);toast(`Could not complete: ${error.message}`);}});
document.addEventListener('submit',async e=>{e.preventDefault();try{if(e.target.id==='search-form'){go('search',encodeURIComponent(new FormData(e.target).get('q').trim()));return;}await saveForm(e.target);}catch(error){console.error(error);toast(`Could not save: ${error.message}`);}});
document.addEventListener('input',e=>{if(e.target.id==='sell-search')filterProducts();if(e.target.id==='catalog-search'){const q=e.target.value.toLowerCase();document.querySelectorAll('#catalog-list [data-search]').forEach(x=>x.hidden=!x.dataset.search.includes(q));}});
document.addEventListener('change',e=>{if(e.target.id==='restore-file'&&e.target.files[0])restore(e.target.files[0]);});
window.addEventListener('hashchange',route);window.addEventListener('online',()=>document.querySelector('#offline').hidden=true);window.addEventListener('offline',()=>document.querySelector('#offline').hidden=false);document.addEventListener('visibilitychange',async()=>{if(document.visibilityState==='visible'&&db){await reconcile();render();}});

async function init(){db=await openDB();if(!(await setting('initialized',false))){await put('settings',{id:'initialized',value:true});await put('settings',{id:'sale_next',value:1});await put('settings',{id:'tax_rate',value:0});await put('settings',{id:'receipt_footer',value:'Thanks for shopping small!'});}await reconcile();document.querySelector('#offline').hidden=navigator.onLine;if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');await route();}
window.BoothBoss={openDB,all,get,put,clear,snapshot,reconcile,saleTotals,eventSummary,validateBackup,populateDemoData,clearDemoData,startTour,skipTour,STORES};
init().catch(error=>{console.error(error);app.innerHTML=`<div class="notice">BoothBoss could not open local storage: ${esc(error.message)}</div>`;});
